### ISSUE TITLE
Using pact-mock-server as mock data provider?

### ISSUE THREAD

**Issue by ichyr** [bethesque/pact-mock_service#35]
**Can I use the pact-mock-service as data-provider for my integration and unit test?**

If it possible to implement the following scenario:
1. Define interactions (in the simplest variant with the same provider and consumer values for different tests)
2. run those consumer contract definitions against pact-mock-server ( e.g. in current implementation run code that will populate the pact files).
3. query pack-mock-server with XHR requests to get responses, from interactions ( from step 0. )

Thus populate the pack-mock-server with interactions and query it for responses from those interactions.

So we will use the interaction definitions as definition of mock data for our tests.

**Comment by ichyr** [comment]
@bethesque sorry for disturbance. I guess the library was not intented to work as I would like it to :) Great job for doing it by the way. I will investigate the ruby source code deeper, becasue this is the most complicated source code that works that I've seen in my life :). I would like to understand how it works. Looks beautiful.

We will use it in the following way to use generated pacts as data-providers for our test:

1. Write down the test in js-dsl
2. run specilized gulp task that will run the pack mock server, run all test with pact js consumer dsl, hut the server.
3. then read the generated pact files in the *onPrepare* method of protractor.js to populate some accessible in all of the e2e test variable
4. use the data from pact.json's in $httpBackend to set up request|response in different use cases.

**Comment by ICEDLEE337** [comment]
This would be a great feature. How is this not possible already?

**Comment by bethesque** [comment]
Mainly because the mock server was not designed to be used in this way, and partially just because of time. We're actually close to being able to use it this way now, as the matching rules for the request are now serialised in the pact. Previously, these were discarded, as they were not needed in the provider verification.

**Comment by ICEDLEE337** [comment]
Understood. This will add tremendous value because it enables accurate, pre-fabbed mocks for developing the client code now with bonafide contracts thereby greatly reducing unknowns at dev time! Personally, I just wrote a simple node service that picks up the outputted Pact json contracts and registers the Pact '$.path' regexes as Express endpoints, which then return the defined Pact response. A basic implementation is like ~40 lines of JS so it wasn't bad at all, but it'll be great to see this feature integrated in the Pact suite. Anyway, thanks and keep up the great work!

**Comment by cbornet** [comment]
@ICEDLEE337 did you see https://github.com/pact-foundation/pact-stub-server ?
