### ISSUE TITLE
Build fails for ruby versions 2.0.0 and 2.1.8: Gem::InstallError: rack requires Ruby version >= 2.2.2.

### ISSUE THREAD

**Issue by sk1talets** [bethesque/pact-mock_service#53]
I'm not sure what is the right way to fix this:
https://travis-ci.org/bethesque/pact-mock_service/builds/149614097
https://travis-ci.org/bethesque/pact-mock_service/builds/149669454

**Comment by sk1talets** [comment]
Or fixing the versions of the dependencies IS the right way?

**Comment by bethesque** [comment]
Hm. Maybe we just drop support for those!

**Comment by sk1talets** [comment]
I also get warnings about that while building gem:
```
WARNING:  open-ended dependency on rack (>= 0) is not recommended
  if rack is semantically versioned, use:
    add_runtime_dependency 'rack', '~> 0'
```
I don't know ruby well enough, but it sounds like it's better to have fixed versions for dependencies? Or should bundler automatically resolve such kind of problems?

**Comment by bethesque** [comment]
Bundler automatically does this. It is good practice to look to a major (or minor) version, but not patch, so that any bug fixes can automatically be used. I think the best thing to do would be to use something like Appraisals and have different gem versions for the different rubies. 

But I'm a bit strapped for time at the moment, so dropping support for the older rubies is probably the best option right now.
